[package]
name = "mousesim"
version = "0.1.0"
edition = "2024"
description = "A mouse movement simulator that generates human-like mouse movements using pre-recorded gesture segments"
license = "Unlicense"

[dependencies]
enigo = "0.6.1"
log = "0.4"
ordered-float = "5.3"
postcard = "1.1"
rstar = "0.13"
thiserror = "2.0"
segments = { path = "../segments" }
