name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            recorder_artifact: recorder
            mousesim_artifact: mousesim
            recorder_asset: recorder-linux-x86_64
            mousesim_asset: mousesim-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            recorder_artifact: recorder.exe
            mousesim_artifact: mousesim.exe
            recorder_asset: recorder-windows-x86_64.exe
            mousesim_asset: mousesim-windows-x86_64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxtst-dev libxinerama-dev libxrandr-dev libxi-dev

      - name: Build recorder binary
        run:
          cargo build --release --target ${{ matrix.target }} --package recorder

      - name: Build mousesim binary
        run:
          cargo build --release --target ${{ matrix.target }} --package mousesim

      - name: Rename binaries
        run: |
          cp ./target/${{ matrix.target }}/release/${{ matrix.recorder_artifact }} ${{ matrix.recorder_asset }}
          cp ./target/${{ matrix.target }}/release/${{ matrix.mousesim_artifact }} ${{ matrix.mousesim_asset }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.recorder_asset }}
            ${{ matrix.mousesim_asset }}
          generate_release_notes: true
